// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwTycASSTABwlzRrh_HmljTTCh4T5xMSs',
    appId: '1:218386038164:web:1ec6cde0bd7e694f722381',
    messagingSenderId: '218386038164',
    projectId: 'navi-e6b9b',
    authDomain: 'navi-e6b9b.firebaseapp.com',
    storageBucket: 'navi-e6b9b.appspot.com',
    measurementId: 'G-4EJ3ZJ2RTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADoQ6wqUL1y-DBjtbUmQAU7STlkNYCikY',
    appId: '1:218386038164:android:d6d7f0cef41f2353722381',
    messagingSenderId: '218386038164',
    projectId: 'navi-e6b9b',
    storageBucket: 'navi-e6b9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG4xq6fgidjyI0Zxf6yeTApuwFrgY0nkg',
    appId: '1:218386038164:ios:cefb4fc5daa0d209722381',
    messagingSenderId: '218386038164',
    projectId: 'navi-e6b9b',
    storageBucket: 'navi-e6b9b.appspot.com',
    iosBundleId: 'com.example.naviProject',
  );
}
